name: "Jason Agel"
cacheVersion: 0001
soundcloudButton: '<iframe allowtransparency="true" scrolling="no" frameborder="no" src="https://w.soundcloud.com/icon/?url=http%3A%2F%2Fsoundcloud.com%2Fjasonagel&color=black_white&size=32" style="width: 32px; height: 32px;"></iframe>'